Repository cheemsjs/hacktoberfest-22, pull requests merged in 2022-10, with the labels that each got.

#1 Add files via upload
  A_Creating_a_Character.cpp
Labels: hacktoberfest-accepted

#2 DrumKit Code
  DrumKit/images/crash.png
  DrumKit/images/drum.gif
  DrumKit/images/drumcat.webp
  DrumKit/images/kick.png
  DrumKit/images/snare.png
  DrumKit/images/tom1.png
  DrumKit/images/tom2.png
  DrumKit/images/tom3.png
  DrumKit/images/tom4.png
  DrumKit/index.html
  DrumKit/index.js
  DrumKit/sounds/crash.mp3
  DrumKit/sounds/kick-bass.mp3
  DrumKit/sounds/snare.mp3
  DrumKit/sounds/tom-1.mp3
  DrumKit/sounds/tom-2.mp3
  DrumKit/sounds/tom-3.mp3
  DrumKit/sounds/tom-4.mp3
  DrumKit/styles.css
Labels: hacktoberfest-accepted

#3 added apartments code
  Apartments.cpp
Labels: hacktoberfest-accepted

#4 Added DP Leetcode guide
  LeetCode Guides/Dynamic_Programming.md
Labels: hacktoberfest-accepted

#5 Leetcode Problem 2139
  2139.minimum-moves-to-reach-target-score.cpp
Labels: hacktoberfest-accepted

#9 Codechef solutions
  CodeChef Solutions/CHEFandDICE.cpp
  CodeChef Solutions/CONSADD.cpp
  CodeChef Solutions/INTERESTINGXOR!.cpp
  CodeChef Solutions/PAPARAZI.cpp
Labels: hacktoberfest-accepted

#8 Feat: Add Atcoder Dynamic Problem Solution Frog1
  AtcoderDP(A)Frog.cpp
Labels: hacktoberfest-accepted

#7 Add files via upload
  216-combination-sum-iii.cpp
Labels: hacktoberfest-accepted

#6 Changed Readme
  README.md
Labels: good first issue, hacktoberfest-accepted

#10 adding solution of array equality
  CodeChef Solutions/Array_Equality.cpp
Labels: hacktoberfest-accepted

#11 Added web dev project
  gta-trilogy/README.md
  gta-trilogy/audio/themeQuiter.ogg
  gta-trilogy/imgs/3a.jpg
  gta-trilogy/imgs/3b.jpg
  gta-trilogy/imgs/3c.jpg
  gta-trilogy/imgs/Grand_Theft_Auto_III_logo.png
  gta-trilogy/imgs/Grand_Theft_Auto_San_Andreas_logo.png
  gta-trilogy/imgs/Grand_Theft_Auto_Vice_City_logo.png
  gta-trilogy/imgs/gta-trilogy.png
  gta-trilogy/imgs/saa.jpg
  gta-trilogy/imgs/sab.jpg
  gta-trilogy/imgs/sac.jpg
  gta-trilogy/imgs/vab.jpg
  gta-trilogy/imgs/vca.jpg
  gta-trilogy/imgs/vcc.jpg
  gta-trilogy/index.html
  gta-trilogy/pricedown bl.otf
  gta-trilogy/style.css
Labels: documentation, good first issue, hacktoberfest-accepted

#14 Create Search_a_2D_Matrix.cpp
  Search_a_2D_Matrix.cpp
Labels: good first issue, hacktoberfest-accepted

#13 Added Binary Tree Codes in C++
  Binary Tree/Binary Tree.cpp
  Binary Tree/Check For Height Balanced BT.cpp
  Binary Tree/Children Sum Property.cpp
  Binary Tree/Construct BT from InOrder and PreOrder.cpp
  Binary Tree/Construct BT from InOrder and PreOrder.exe
  Binary Tree/Convert BT to DLL.cpp
  Binary Tree/Height of BT.cpp
  Binary Tree/In Order Traversal.cpp
  Binary Tree/Level Order Traversal Line by Line Part 1.cpp
  Binary Tree/Level Order Traversal Line by Line Part 2.cpp
  Binary Tree/Level Order Traversal.cpp
  Binary Tree/Maximum Width of BT.cpp
  Binary Tree/Maximum in BT.cpp
  Binary Tree/Post Order Traversal.cpp
  Binary Tree/Pre Order Traversal.cpp
  Binary Tree/Print Left View of BT.cpp
  Binary Tree/Print Nodes at K Distance.cpp
  Binary Tree/Size of BT.cpp
Labels: hacktoberfest-accepted

#18 Create insertion sort
  insertion_sort.cpp
Labels: hacktoberfest-accepted
